---
--- Generated by Luanalysis
--- Created by marcelo.
--- DateTime: 21/01/2021 18:00
---

local cjson = require("cjson")

local json_foo = cjson.decode(string_foo)
local ids = {}
for idx, ele in pairs(json_foo) do
    ids[idx] = ele["id"]
end
return ids